package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.93

import (
	"context"
	"errors"
	"fmt"
	"slices"

	"github.com/brian-bell/flowstate/flowlaunch"
	"github.com/brian-bell/flowstate/flowstore"
	"github.com/brian-bell/flowstate/internal/artifacts"
	"github.com/brian-bell/flowstate/server/flowquery"
	"github.com/brian-bell/flowstate/server/graph/generated"
	"github.com/brian-bell/flowstate/server/graph/model"
	"github.com/brian-bell/flowstate/server/runtimejobs"
)

// CreateFlow is the resolver for the createFlow field.
func (r *mutationResolver) CreateFlow(ctx context.Context, input model.CreateFlowInput) (*model.Flow, error) {
	if r.FlowCreator == nil {
		return nil, fmt.Errorf("flow creator is not configured")
	}
	baseRef := ""
	if input.BaseRef != nil {
		baseRef = *input.BaseRef
	}
	record, err := r.FlowCreator.CreateFlow(ctx, CreateFlowInput{
		RepoPath:     input.RepoPath,
		Title:        input.Title,
		Instructions: input.Instructions,
		BaseRef:      baseRef,
	})
	if err != nil {
		return nil, err
	}
	view, err := flowquery.BuildWithRuntime(record, r.RuntimeJobs)
	if err != nil {
		view = flowquery.Build(record)
	}
	return flowToGraphQL(view), nil
}

// CreateFlowAndLaunchPlan is the resolver for the createFlowAndLaunchPlan field.
func (r *mutationResolver) CreateFlowAndLaunchPlan(ctx context.Context, input model.CreateFlowAndLaunchPlanInput) (*model.CreateFlowAndLaunchPlanPayload, error) {
	if r.FlowCreator == nil {
		return nil, fmt.Errorf("flow creator is not configured")
	}
	if r.FlowStore == nil {
		return nil, fmt.Errorf("flow store is not configured")
	}
	if r.RuntimeStarter == nil {
		return nil, fmt.Errorf("runtime job starter is not configured")
	}
	command, err := r.launchAgentCommand(input.AgentCommand)
	if err != nil {
		return nil, err
	}
	reasoningEffort, err := r.launchReasoningEffort(command, input.ReasoningEffort)
	if err != nil {
		return nil, err
	}
	baseRef := ""
	if input.BaseRef != nil {
		baseRef = *input.BaseRef
	}
	record, err := r.FlowCreator.CreateFlow(ctx, CreateFlowInput{
		RepoPath:     input.RepoPath,
		Title:        input.Title,
		Instructions: input.Instructions,
		BaseRef:      baseRef,
	})
	if err != nil {
		return nil, err
	}
	phase, ok := flowlaunch.PhaseByID(record, "plan")
	if !ok {
		return nil, fmt.Errorf("phase %q not found in flow %q", "plan", record.FlowID)
	}
	if phase.Status == flowstore.PhaseBlocked {
		view, err := flowquery.BuildWithRuntime(record, r.RuntimeJobs)
		if err != nil {
			view = flowquery.Build(record)
		}
		return &model.CreateFlowAndLaunchPlanPayload{Flow: flowToGraphQL(view)}, nil
	}
	if !flowlaunch.PhaseCanLaunch(record, phase) {
		return nil, fmt.Errorf("phase %q is not launchable from status %q", phase.PhaseID, phase.Status)
	}
	launch, err := r.startFlowRuntimeJob(ctx, record, phase, command, reasoningEffort)
	if err != nil {
		var startErr *flowRuntimeStartError
		if !errors.As(err, &startErr) {
			return nil, err
		}
		updated, readErr := r.FlowStore.Read(record.FlowID)
		if readErr != nil {
			return nil, readErr
		}
		view, buildErr := flowquery.BuildWithRuntime(updated, r.RuntimeJobs)
		if buildErr != nil {
			view = flowquery.Build(updated)
		}
		launchID := launch.Context.LaunchID
		return &model.CreateFlowAndLaunchPlanPayload{
			Flow:        flowToGraphQL(view),
			LaunchID:    &launchID,
			LaunchError: startErr.err.Error(),
		}, nil
	}
	updated, err := r.FlowStore.Read(record.FlowID)
	if err != nil {
		return nil, err
	}
	view, err := flowquery.BuildWithRuntime(updated, r.RuntimeJobs)
	if err != nil {
		view = flowquery.Build(updated)
	}
	launchID := launch.Context.LaunchID
	return &model.CreateFlowAndLaunchPlanPayload{
		Flow:        flowToGraphQL(view),
		LaunchID:    &launchID,
		Job:         runtimeJobSnapshotToGraphQL(launch.Snapshot),
		LaunchError: "",
	}, nil
}

// LaunchFlowPhase is the resolver for the launchFlowPhase field.
func (r *mutationResolver) LaunchFlowPhase(ctx context.Context, input model.LaunchFlowPhaseInput) (*model.LaunchFlowPhasePayload, error) {
	if r.FlowStore == nil {
		return nil, fmt.Errorf("flow store is not configured")
	}
	if r.RuntimeStarter == nil {
		return nil, fmt.Errorf("runtime job starter is not configured")
	}
	record, err := r.FlowStore.Read(input.FlowID)
	if err != nil {
		return nil, err
	}
	phase, ok := flowlaunch.PhaseByID(record, input.PhaseID)
	if !ok {
		return nil, fmt.Errorf("phase %q not found in flow %q", input.PhaseID, input.FlowID)
	}
	if !flowlaunch.PhaseCanLaunch(record, phase) {
		return nil, fmt.Errorf("phase %q is not launchable from status %q", phase.PhaseID, phase.Status)
	}
	command, err := r.launchAgentCommand(input.AgentCommand)
	if err != nil {
		return nil, err
	}
	reasoningEffort, err := r.launchReasoningEffort(command, input.ReasoningEffort)
	if err != nil {
		return nil, err
	}
	launch, err := r.startFlowRuntimeJob(ctx, record, phase, command, reasoningEffort)
	if err != nil {
		return nil, err
	}
	return &model.LaunchFlowPhasePayload{
		FlowID:   record.FlowID,
		PhaseID:  launch.Context.FlowPhaseID,
		LaunchID: launch.Context.LaunchID,
		Job:      runtimeJobSnapshotToGraphQL(launch.Snapshot),
	}, nil
}

// CancelRuntimeJob is the resolver for the cancelRuntimeJob field.
func (r *mutationResolver) CancelRuntimeJob(ctx context.Context, id string) (*model.RuntimeJob, error) {
	if r.RuntimeController == nil {
		return nil, fmt.Errorf("runtime job controller is not configured")
	}
	result := r.RuntimeController.Cancel(id)
	switch result.Code {
	case runtimejobs.CancelCanceled:
		return runtimeJobSnapshotToGraphQL(result.Snapshot), nil
	case runtimejobs.CancelAlreadyTerminal:
		return nil, fmt.Errorf("runtime job %q is already terminal with status %q", id, result.Snapshot.Status)
	case runtimejobs.CancelInvalidID:
		return nil, fmt.Errorf("runtime job id is required")
	case runtimejobs.CancelNotFound:
		return nil, fmt.Errorf("runtime job %q not found", id)
	default:
		if result.Code == "" && result.Found && result.Transition && result.Snapshot.Status == runtimejobs.StatusCanceled {
			return runtimeJobSnapshotToGraphQL(result.Snapshot), nil
		}
		if !result.Found {
			return nil, fmt.Errorf("runtime job %q not found", id)
		}
		return nil, fmt.Errorf("runtime job %q could not be canceled", id)
	}
}

// SetFlowPhaseStatus is the resolver for the setFlowPhaseStatus field.
func (r *mutationResolver) SetFlowPhaseStatus(ctx context.Context, input model.SetFlowPhaseStatusInput) (*model.SetFlowPhaseStatusPayload, error) {
	if r.FlowStore == nil {
		return nil, fmt.Errorf("flow store is not configured")
	}
	update := flowstore.PhaseUpdate{
		FlowID:  input.FlowID,
		PhaseID: input.PhaseID,
		Status:  flowPhaseStatusInputToStore(input.Status),
	}
	if input.Outcome != nil {
		update.Outcome = *input.Outcome
	}
	if input.Notes != nil {
		update.Notes = *input.Notes
	}
	if input.Summary != nil {
		update.Summary = *input.Summary
	}
	record, err := r.FlowStore.SetPhase(update)
	if err != nil {
		return nil, fmt.Errorf("set flow phase status %q/%q: %w", input.FlowID, input.PhaseID, err)
	}
	view, err := flowquery.BuildWithRuntime(record, r.RuntimeJobs)
	if err != nil {
		view = flowquery.Build(record)
	}
	phaseID := artifacts.NormalizePhaseID(input.PhaseID)
	for _, phase := range view.Phases {
		if artifacts.NormalizePhaseID(phase.PhaseID) == phaseID {
			return &model.SetFlowPhaseStatusPayload{
				Flow:  flowToGraphQL(view),
				Phase: phaseToGraphQL(phase),
			}, nil
		}
	}
	return nil, fmt.Errorf("set flow phase status %q/%q: updated phase not found", input.FlowID, input.PhaseID)
}

// Health is the resolver for the health field.
func (r *queryResolver) Health(ctx context.Context) (string, error) {
	return "ok", nil
}

// Flows is the resolver for the flows field.
func (r *queryResolver) Flows(ctx context.Context, statuses []model.FlowStatus) ([]*model.Flow, error) {
	if r.FlowStore == nil {
		return nil, fmt.Errorf("flow store is not configured")
	}
	records, err := r.FlowStore.List(flowstore.FlowFilter{})
	if err != nil {
		return nil, err
	}
	allowed := make([]string, 0, len(statuses))
	for _, status := range statuses {
		allowed = append(allowed, flowStatusInputToStore(status))
	}
	flows := make([]*model.Flow, 0, len(records))
	for _, record := range records {
		if len(allowed) > 0 && !slices.Contains(allowed, record.Status) {
			continue
		}
		view, err := flowquery.BuildWithRuntime(record, r.RuntimeJobs)
		if err != nil {
			return nil, err
		}
		flows = append(flows, flowToGraphQL(view))
	}
	return flows, nil
}

// Flow is the resolver for the flow field.
func (r *queryResolver) Flow(ctx context.Context, id string) (*model.Flow, error) {
	if r.FlowStore == nil {
		return nil, fmt.Errorf("flow store is not configured")
	}
	record, err := r.FlowStore.Read(id)
	if err != nil {
		if flowstore.IsNotFound(err) {
			return nil, nil
		}
		return nil, err
	}
	view, err := flowquery.BuildWithRuntime(record, r.RuntimeJobs)
	if err != nil {
		return nil, err
	}
	flow := flowToGraphQL(view)
	return flow, nil
}

// Mutation returns generated.MutationResolver implementation.
func (r *Resolver) Mutation() generated.MutationResolver { return &mutationResolver{r} }

// Query returns generated.QueryResolver implementation.
func (r *Resolver) Query() generated.QueryResolver { return &queryResolver{r} }

type (
	mutationResolver struct{ *Resolver }
	queryResolver    struct{ *Resolver }
)
