package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.93

import (
	"context"
	"fmt"
	"slices"

	"github.com/brian-bell/flowstate/flowstore"
	"github.com/brian-bell/flowstate/server/flowquery"
	"github.com/brian-bell/flowstate/server/graph/generated"
	"github.com/brian-bell/flowstate/server/graph/model"
)

// CreateFlow is the resolver for the createFlow field.
func (r *mutationResolver) CreateFlow(ctx context.Context, input model.CreateFlowInput) (*model.Flow, error) {
	if r.FlowCreator == nil {
		return nil, fmt.Errorf("flow creator is not configured")
	}
	baseRef := ""
	if input.BaseRef != nil {
		baseRef = *input.BaseRef
	}
	record, err := r.FlowCreator.CreateFlow(ctx, CreateFlowInput{
		RepoPath:     input.RepoPath,
		Title:        input.Title,
		Instructions: input.Instructions,
		BaseRef:      baseRef,
	})
	if err != nil {
		return nil, err
	}
	view, err := flowquery.BuildWithRuntime(record, r.RuntimeJobs)
	if err != nil {
		return nil, err
	}
	return flowToGraphQL(view), nil
}

// Health is the resolver for the health field.
func (r *queryResolver) Health(ctx context.Context) (string, error) {
	return "ok", nil
}

// Flows is the resolver for the flows field.
func (r *queryResolver) Flows(ctx context.Context, statuses []model.FlowStatus) ([]*model.Flow, error) {
	if r.FlowReader == nil {
		return nil, fmt.Errorf("flow reader is not configured")
	}
	records, err := r.FlowReader.List(flowstore.FlowFilter{})
	if err != nil {
		return nil, err
	}
	allowed := make([]string, 0, len(statuses))
	for _, status := range statuses {
		allowed = append(allowed, flowStatusInputToStore(status))
	}
	flows := make([]*model.Flow, 0, len(records))
	for _, record := range records {
		if len(allowed) > 0 && !slices.Contains(allowed, record.Status) {
			continue
		}
		view, err := flowquery.BuildWithRuntime(record, r.RuntimeJobs)
		if err != nil {
			return nil, err
		}
		flows = append(flows, flowToGraphQL(view))
	}
	return flows, nil
}

// Flow is the resolver for the flow field.
func (r *queryResolver) Flow(ctx context.Context, id string) (*model.Flow, error) {
	if r.FlowReader == nil {
		return nil, fmt.Errorf("flow reader is not configured")
	}
	record, err := r.FlowReader.Read(id)
	if err != nil {
		if flowstore.IsNotFound(err) {
			return nil, nil
		}
		return nil, err
	}
	view, err := flowquery.BuildWithRuntime(record, r.RuntimeJobs)
	if err != nil {
		return nil, err
	}
	flow := flowToGraphQL(view)
	return flow, nil
}

// Mutation returns generated.MutationResolver implementation.
func (r *Resolver) Mutation() generated.MutationResolver { return &mutationResolver{r} }

// Query returns generated.QueryResolver implementation.
func (r *Resolver) Query() generated.QueryResolver { return &queryResolver{r} }

type (
	mutationResolver struct{ *Resolver }
	queryResolver    struct{ *Resolver }
)
